name: MiniStudio
options:
  bundleIdPrefix: com.abdi
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY: '1,2'
    CODE_SIGNING_ALLOWED: NO
targets:
  MiniStudio:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - StudioBrowser.swift
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abdi.ministudio
        MARKETING_VERSION: '2.3.0'
        CURRENT_PROJECT_VERSION: '14'
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      gatherCoverageData: false
